### ISSUE TITLE
Specflow 2.2

### ISSUE THREAD

**Issue by Icaroto** [gasparnagy/SpecFlow.Autofac#9]
Hi

I wanted to ask if is there any plan to make it work with Specflow 2.2? 

Right now, even using the pull request from @zaccharles (https://github.com/gasparnagy/SpecFlow.Autofac/pull/7) I still face some issues when my BeforeFeature hook has FeatureContext as parameter to be resolved.

Basically it goes to **ResolveBindingInstance** before registering scenario/feature in runtimePluginEvents.CustomizeScenarioDependencies 

That only happens if you are using 2.2 Specflowchanges (Like I mentioned, BeforeFeature with feature context as parameter)

Thanks!

**Comment by gasparnagy** [comment]
@Icaroto yes. i will try to make it in one of my evenings next week.

**Comment by elenatosheva** [comment]
Hi,
I also want to ask you about Specflow 2.2 version support?
Do you have any plans to include it in the feature versions and eventually when?

Otherwise is there a workaround to use Autofac with Specflow 2.2?

Regards,
Elena

**Comment by matthiaslischka** [comment]
Hi Gaspar,
any updates on the Specflow 2.2 support? I saw you merged https://github.com/gasparnagy/SpecFlow.Autofac/pull/7 but at least the NuGet Package still has 2.1. as dependency.

BR,
Matthias

**Comment by gasparnagy** [comment]
@matthiaslischka @elenatosheva The upgrade was done a couple of days ago (just forgot to push). I was struggling with #6, that turned out to be a more generic issue (or even two), but I have a workaround at least.

I will make a pre-release now. If anyone could look at the other open issues that would be great.

**Comment by gasparnagy** [comment]
https://www.nuget.org/packages/SpecFlow.Autofac/1.1.0-pre20171024
